update countries set short_name = 'AD' , name_en = 'Andorra' , name_ar = 'أندورا' where id = 'AD';
update countries set short_name = 'AE' , name_en = 'United Arab Emirates' , name_ar = 'الإمارات العربية المتحدة ' where id = 'AE';
update countries set short_name = 'AF' , name_en = 'Afghanistan' , name_ar = 'أفغانستان' where id = 'AF';
update countries set short_name = 'AG' , name_en = 'Antigua and Barbuda' , name_ar = 'أنتيغوا وبربودا' where id = 'AG';
update countries set short_name = 'AL' , name_en = 'Albania' , name_ar = 'ألبانيا ' where id = 'AL';
update countries set short_name = 'AM' , name_en = 'Armenia' , name_ar = 'أرمينيا ' where id = 'AM';
update countries set short_name = 'AO' , name_en = 'Angola' , name_ar = 'أنغولا ' where id = 'AO';
update countries set short_name = 'AR' , name_en = 'Argentina' , name_ar = 'الأرجنتين ' where id = 'AR';
update countries set short_name = 'AS' , name_en = 'American Samoa' , name_ar = 'ساموا الأمريكية' where id = 'AS';
update countries set short_name = 'AT' , name_en = 'Austria' , name_ar = 'النمسا ' where id = 'AT';
update countries set short_name = 'AU' , name_en = 'Australia' , name_ar = 'أستراليا ' where id = 'AU';
update countries set short_name = 'AW' , name_en = 'Aruba' , name_ar = 'أروبا' where id = 'AW';
update countries set short_name = 'AZ' , name_en = 'Azerbaijan' , name_ar = 'أذربيجان ' where id = 'AZ';
update countries set short_name = 'BA' , name_en = 'Bosnia and Herzegovina' , name_ar = 'البوسنة والهرسك ' where id = 'BA';
update countries set short_name = 'BB' , name_en = 'Barbados' , name_ar = 'بربادوس ' where id = 'BB';
update countries set short_name = 'BD' , name_en = 'Bangladesh' , name_ar = 'بنغلاديش ' where id = 'BD';
update countries set short_name = 'BE' , name_en = 'Belgium' , name_ar = 'بلجيكا ' where id = 'BE';
update countries set short_name = 'BF' , name_en = 'Burkina Faso' , name_ar = 'بوركينا فاسو ' where id = 'BF';
update countries set short_name = 'BG' , name_en = 'Bulgaria' , name_ar = 'بلغاريا ' where id = 'BG';
update countries set short_name = 'BH' , name_en = 'Bahrain' , name_ar = 'البحرين ' where id = 'BH';
update countries set short_name = 'BI' , name_en = 'Burundi' , name_ar = 'بوروندي ' where id = 'BI';
update countries set short_name = 'BJ' , name_en = 'Benin' , name_ar = 'بنين ' where id = 'BJ';
update countries set short_name = 'BM' , name_en = 'Bermuda' , name_ar = 'برمودا' where id = 'BM';
update countries set short_name = 'BN' , name_en = 'Brunei Darussalam' , name_ar = 'بروناي دار السلام ' where id = 'BN';
update countries set short_name = 'BO' , name_en = 'Bolivia' , name_ar = 'بوليفيا ' where id = 'BO';
update countries set short_name = 'BR' , name_en = 'Brazil' , name_ar = 'البرازيل ' where id = 'BR';
update countries set short_name = 'BS' , name_en = 'Bahamas' , name_ar = 'جزر البهاما' where id = 'BS';
update countries set short_name = 'BT' , name_en = 'Bhutan' , name_ar = 'بوتان ' where id = 'BT';
update countries set short_name = 'BW' , name_en = 'Botswana' , name_ar = 'بوتسوانا ' where id = 'BW';
update countries set short_name = 'BY' , name_en = 'Belarus' , name_ar = 'روسيا البيضاء' where id = 'BY';
update countries set short_name = 'BZ' , name_en = 'Belize' , name_ar = 'بليز' where id = 'BZ';
update countries set short_name = 'CA' , name_en = 'Canada' , name_ar = 'كندا ' where id = 'CA';
update countries set short_name = 'CD' , name_en = 'Democratic Republic of the Congo' , name_ar = 'الكونغو (جمهورية الكونغو الديمقراطية)' where id = 'CD';
update countries set short_name = 'CF' , name_en = 'Central African Republic' , name_ar = 'جمهورية أفريقيا الوسطى' where id = 'CF';
update countries set short_name = 'CG' , name_en = 'Congo' , name_ar = 'الكونغو' where id = 'CG';
update countries set short_name = 'CH' , name_en = 'Switzerland' , name_ar = 'سويسرا ' where id = 'CH';
update countries set short_name = 'CI' , name_en = 'Ivory Coast' , name_ar = 'ساحل العاج' where id = 'CI';
update countries set short_name = 'CL' , name_en = 'Chile' , name_ar = 'تشيلي ' where id = 'CL';
update countries set short_name = 'CM' , name_en = 'Cameroon' , name_ar = 'الكاميرون ' where id = 'CM';
update countries set short_name = 'CN' , name_en = 'China' , name_ar = 'الصين ' where id = 'CN';
update countries set short_name = 'CO' , name_en = 'Colombia' , name_ar = 'كولومبيا ' where id = 'CO';
update countries set short_name = 'CR' , name_en = 'Costa Rica' , name_ar = 'كوستاريكا ' where id = 'CR';
update countries set short_name = 'CU' , name_en = 'Cuba' , name_ar = 'كوبا' where id = 'CU';
update countries set short_name = 'CV' , name_en = 'Cape Verde' , name_ar = 'الرأس الأخضر ' where id = 'CV';
update countries set short_name = 'CW' , name_en = 'Curacao' , name_ar = 'كوراسو' where id = 'CW';
update countries set short_name = 'CY' , name_en = 'Cyprus' , name_ar = 'قبرص ' where id = 'CY';
update countries set short_name = 'CZ' , name_en = 'Czech Republic' , name_ar = 'جمهورية التشيك ' where id = 'CZ';
update countries set short_name = 'DE' , name_en = 'Germany' , name_ar = 'ألمانيا ' where id = 'DE';
update countries set short_name = 'DJ' , name_en = 'Djibouti' , name_ar = 'جيبوتي' where id = 'DJ';
update countries set short_name = 'DK' , name_en = 'Denmark' , name_ar = 'الدنمارك ' where id = 'DK';
update countries set short_name = 'DM' , name_en = 'Dominica' , name_ar = 'دومينيكا' where id = 'DM';
update countries set short_name = 'DO' , name_en = 'Dominican Republic' , name_ar = 'جمهورية الدومينيكان ' where id = 'DO';
update countries set short_name = 'DZ' , name_en = 'Algeria' , name_ar = 'الجزائر ' where id = 'DZ';
update countries set short_name = 'EC' , name_en = 'Ecuador' , name_ar = 'الإكوادور ' where id = 'EC';
update countries set short_name = 'EE' , name_en = 'Estonia' , name_ar = 'استونيا ' where id = 'EE';
update countries set short_name = 'EG' , name_en = 'Egypt' , name_ar = 'مصر ' where id = 'EG';
update countries set short_name = 'ER' , name_en = 'Eritrea' , name_ar = 'إريتريا' where id = 'ER';
update countries set short_name = 'ES' , name_en = 'Spain' , name_ar = 'اسبانيا ' where id = 'ES';
update countries set short_name = 'ET' , name_en = 'Ethiopia' , name_ar = 'إثيوبيا ' where id = 'ET';
update countries set short_name = 'FI' , name_en = 'Finland' , name_ar = 'فنلندا ' where id = 'FI';
update countries set short_name = 'FJ' , name_en = 'Fiji' , name_ar = 'فيجي' where id = 'FJ';
update countries set short_name = 'FM' , name_en = 'Micronesia' , name_ar = 'ميكرونيزيا (ولايات)' where id = 'FM';
update countries set short_name = 'FO' , name_en = 'Faroe Islands' , name_ar = 'جزر فارو' where id = 'FO';
update countries set short_name = 'FR' , name_en = 'France' , name_ar = 'فرنسا ' where id = 'FR';
update countries set short_name = 'GA' , name_en = 'Gabon' , name_ar = 'الغابون ' where id = 'GA';
update countries set short_name = 'GB' , name_en = 'United Kingdom' , name_ar = 'المملكة المتحدة ' where id = 'GB';
update countries set short_name = 'GD' , name_en = 'Grenada' , name_ar = 'غرينادا' where id = 'GD';
update countries set short_name = 'GE' , name_en = 'Georgia' , name_ar = 'جورجيا ' where id = 'GE';
update countries set short_name = 'GH' , name_en = 'Ghana' , name_ar = 'غانا ' where id = 'GH';
update countries set short_name = 'GI' , name_en = 'Gibraltar' , name_ar = 'جبل طارق' where id = 'GI';
update countries set short_name = 'GL' , name_en = 'Greenland' , name_ar = 'جرينلاند' where id = 'GL';
update countries set short_name = 'GM' , name_en = 'Gambia' , name_ar = 'غامبيا ' where id = 'GM';
update countries set short_name = 'GN' , name_en = 'Guinea' , name_ar = 'غينيا ' where id = 'GN';
update countries set short_name = 'GQ' , name_en = 'Equatorial Guinea' , name_ar = 'غينيا الاستوائية' where id = 'GQ';
update countries set short_name = 'GR' , name_en = 'Greece' , name_ar = 'اليونان ' where id = 'GR';
update countries set short_name = 'GT' , name_en = 'Guatemala' , name_ar = 'غواتيمالا ' where id = 'GT';
update countries set short_name = 'GU' , name_en = 'Guam' , name_ar = 'جوام' where id = 'GU';
update countries set short_name = 'GW' , name_en = 'Guinea-Bissau' , name_ar = 'غينيا بيساو' where id = 'GW';
update countries set short_name = 'GY' , name_en = 'Guyana' , name_ar = 'غيانا ' where id = 'GY';
update countries set short_name = 'HK' , name_en = 'Hong Kong SAR' , name_ar = 'هونج كونج SAR ' where id = 'HK';
update countries set short_name = 'HN' , name_en = 'Honduras' , name_ar = 'هندوراس ' where id = 'HN';
update countries set short_name = 'HR' , name_en = 'Croatia' , name_ar = 'كرواتيا ' where id = 'HR';
update countries set short_name = 'HT' , name_en = 'Haiti' , name_ar = 'هايتي ' where id = 'HT';
update countries set short_name = 'HU' , name_en = 'Hungary' , name_ar = 'المجر ' where id = 'HU';
update countries set short_name = 'ID' , name_en = 'Indonesia' , name_ar = 'اندونيسيا ' where id = 'ID';
update countries set short_name = 'IE' , name_en = 'Ireland' , name_ar = 'ايرلندا ' where id = 'IE';
update countries set short_name = 'IL' , name_en = 'Israel' , name_ar = 'إسرائيل' where id = 'IL';
update countries set short_name = 'IM' , name_en = 'Isle of Man' , name_ar = 'جزيرة مان' where id = 'IM';
update countries set short_name = 'IN' , name_en = 'India' , name_ar = 'الهند ' where id = 'IN';
update countries set short_name = 'IQ' , name_en = 'Iraq' , name_ar = 'العراق' where id = 'IQ';
update countries set short_name = 'IR' , name_en = 'Iran' , name_ar = 'جمهورية إيران الإسلامية ' where id = 'IR';
update countries set short_name = 'IS' , name_en = 'Iceland' , name_ar = 'أيسلندا ' where id = 'IS';
update countries set short_name = 'IT' , name_en = 'Italy' , name_ar = 'إيطاليا ' where id = 'IT';
update countries set short_name = 'JG' , name_en = 'Channel Islands' , name_ar = 'جزر القنال' where id = 'JG';
update countries set short_name = 'JM' , name_en = 'Jamaica' , name_ar = 'جامايكا ' where id = 'JM';
update countries set short_name = 'JO' , name_en = 'Jordan' , name_ar = 'الأردن ' where id = 'JO';
update countries set short_name = 'JP' , name_en = 'Japan' , name_ar = 'اليابان ' where id = 'JP';
update countries set short_name = 'KE' , name_en = 'Kenya' , name_ar = 'كينيا ' where id = 'KE';
update countries set short_name = 'KG' , name_en = 'Kyrgyz Republic' , name_ar = 'جمهورية قيرغيزستان ' where id = 'KG';
update countries set short_name = 'KH' , name_en = 'Cambodia' , name_ar = 'كمبوديا ' where id = 'KH';
update countries set short_name = 'KI' , name_en = 'Kiribati' , name_ar = 'كيريباس' where id = 'KI';
update countries set short_name = 'KM' , name_en = 'Comoros' , name_ar = 'جزر القمر' where id = 'KM';
update countries set short_name = 'KN' , name_en = 'Saint Kitts and Nevis' , name_ar = 'سانت كيتس ونيفيس' where id = 'KN';
update countries set short_name = 'KP' , name_en = 'North Korea' , name_ar = 'كوريا الشمالية' where id = 'KP';
update countries set short_name = 'KR' , name_en = 'Korea Republic' , name_ar = 'كوريا الجنوبية' where id = 'KR';
update countries set short_name = 'KW' , name_en = 'Kuwait' , name_ar = 'الكويت ' where id = 'KW';
update countries set short_name = 'KY' , name_en = 'Cayman Islands' , name_ar = 'جزر الكايمن' where id = 'KY';
update countries set short_name = 'KZ' , name_en = 'Kazakhstan' , name_ar = 'كازاخستان ' where id = 'KZ';
update countries set short_name = 'LA' , name_en = 'Lao PDR' , name_ar = 'جمهورية لاو الديمقراطية الشعبية ' where id = 'LA';
update countries set short_name = 'LB' , name_en = 'Lebanon' , name_ar = 'لبنان ' where id = 'LB';
update countries set short_name = 'LC' , name_en = 'Saint Lucia' , name_ar = 'سانت لوسيا' where id = 'LC';
update countries set short_name = 'LI' , name_en = 'Liechtenstein' , name_ar = 'ليختنشتاين' where id = 'LI';
update countries set short_name = 'LK' , name_en = 'Sri Lanka' , name_ar = 'سري لانكا ' where id = 'LK';
update countries set short_name = 'LR' , name_en = 'Liberia' , name_ar = 'ليبيريا ' where id = 'LR';
update countries set short_name = 'LS' , name_en = 'Lesotho' , name_ar = 'ليسوتو ' where id = 'LS';
update countries set short_name = 'LT' , name_en = 'Lithuania' , name_ar = 'ليتوانيا ' where id = 'LT';
update countries set short_name = 'LU' , name_en = 'Luxembourg' , name_ar = 'لوكسمبورغ ' where id = 'LU';
update countries set short_name = 'LV' , name_en = 'Latvia' , name_ar = 'لاتفيا ' where id = 'LV';
update countries set short_name = 'LY' , name_en = 'Libya' , name_ar = 'ليبيا ' where id = 'LY';
update countries set short_name = 'MA' , name_en = 'Morocco' , name_ar = 'المغرب ' where id = 'MA';
update countries set short_name = 'MC' , name_en = 'Monaco' , name_ar = 'موناكو' where id = 'MC';
update countries set short_name = 'MD' , name_en = 'Moldova' , name_ar = 'مولدوفا ' where id = 'MD';
update countries set short_name = 'ME' , name_en = 'Montenegro' , name_ar = 'الجبل الأسود ' where id = 'ME';
update countries set short_name = 'MF' , name_en = 'St. Martin (French part)' , name_ar = 'سانت مارتن (الفرنسية)' where id = 'MF';
update countries set short_name = 'MG' , name_en = 'Madagascar' , name_ar = 'مدغشقر ' where id = 'MG';
update countries set short_name = 'MH' , name_en = 'Marshall Islands' , name_ar = 'جزر مارشال' where id = 'MH';
update countries set short_name = 'MK' , name_en = 'Macedonia' , name_ar = 'جمهورية مقدونيا اليوغوسلافية السابقة ' where id = 'MK';
update countries set short_name = 'ML' , name_en = 'Mali' , name_ar = 'مالي ' where id = 'ML';
update countries set short_name = 'MM' , name_en = 'Myanmar' , name_ar = 'ميانمار ' where id = 'MM';
update countries set short_name = 'MN' , name_en = 'Mongolia' , name_ar = 'منغوليا ' where id = 'MN';
update countries set short_name = 'MO' , name_en = 'Macao' , name_ar = 'ماكاو' where id = 'MO';
update countries set short_name = 'MP' , name_en = 'Northern Mariana Islands' , name_ar = 'جزر ماريانا الشمالية' where id = 'MP';
update countries set short_name = 'MR' , name_en = 'Mauritania' , name_ar = 'موريتانيا ' where id = 'MR';
update countries set short_name = 'MT' , name_en = 'Malta' , name_ar = 'مالطا ' where id = 'MT';
update countries set short_name = 'MU' , name_en = 'Mauritius' , name_ar = 'موريشيوس ' where id = 'MU';
update countries set short_name = 'MV' , name_en = 'Maldives' , name_ar = 'جزر المالديف' where id = 'MV';
update countries set short_name = 'MW' , name_en = 'Malawi' , name_ar = 'مالاوي ' where id = 'MW';
update countries set short_name = 'MX' , name_en = 'Mexico' , name_ar = 'المكسيك ' where id = 'MX';
update countries set short_name = 'MY' , name_en = 'Malaysia' , name_ar = 'ماليزيا ' where id = 'MY';
update countries set short_name = 'MZ' , name_en = 'Mozambique' , name_ar = 'موزمبيق ' where id = 'MZ';
update countries set short_name = 'NA' , name_en = 'Namibia' , name_ar = 'ناميبيا ' where id = 'NA';
update countries set short_name = 'NC' , name_en = 'New Caledonia' , name_ar = 'كاليدونيا الجديدة' where id = 'NC';
update countries set short_name = 'NE' , name_en = 'Niger' , name_ar = 'النيجر' where id = 'NE';
update countries set short_name = 'NG' , name_en = 'Nigeria' , name_ar = 'نيجيريا ' where id = 'NG';
update countries set short_name = 'NI' , name_en = 'Nicaragua' , name_ar = 'نيكاراغوا ' where id = 'NI';
update countries set short_name = 'NL' , name_en = 'Netherlands' , name_ar = 'هولندا ' where id = 'NL';
update countries set short_name = 'NO' , name_en = 'Norway' , name_ar = 'النرويج ' where id = 'NO';
update countries set short_name = 'NP' , name_en = 'Nepal' , name_ar = 'نيبال ' where id = 'NP';
update countries set short_name = 'NR' , name_en = 'Nauru' , name_ar = 'ناورو' where id = 'NR';
update countries set short_name = 'NZ' , name_en = 'New Zealand' , name_ar = 'نيوزيلندا ' where id = 'NZ';
update countries set short_name = 'OM' , name_en = 'Oman' , name_ar = 'عمان ' where id = 'OM';
update countries set short_name = 'PA' , name_en = 'Panama' , name_ar = 'بنما ' where id = 'PA';
update countries set short_name = 'PE' , name_en = 'Peru' , name_ar = 'بيرو ' where id = 'PE';
update countries set short_name = 'PF' , name_en = 'French Polynesia' , name_ar = 'بولينيزيا الفرنسية' where id = 'PF';
update countries set short_name = 'PG' , name_en = 'Papua New Guinea' , name_ar = 'بابوا غينيا الجديدة' where id = 'PG';
update countries set short_name = 'PH' , name_en = 'Philippines' , name_ar = 'الفلبين ' where id = 'PH';
update countries set short_name = 'PK' , name_en = 'Pakistan' , name_ar = 'باكستان ' where id = 'PK';
update countries set short_name = 'PL' , name_en = 'Poland' , name_ar = 'بولندا ' where id = 'PL';
update countries set short_name = 'PR' , name_en = 'Puerto Rico' , name_ar = 'بويرتو ريكو ' where id = 'PR';
update countries set short_name = 'PS' , name_en = 'Palestine' , name_ar = 'فلسطين، دولة' where id = 'PS';
update countries set short_name = 'PT' , name_en = 'Portugal' , name_ar = 'البرتغال ' where id = 'PT';
update countries set short_name = 'PW' , name_en = 'Palau' , name_ar = 'بالاو' where id = 'PW';
update countries set short_name = 'PY' , name_en = 'Paraguay' , name_ar = 'باراغواي ' where id = 'PY';
update countries set short_name = 'QA' , name_en = 'Qatar' , name_ar = 'قطر ' where id = 'QA';
update countries set short_name = 'RO' , name_en = 'Romania' , name_ar = 'رومانيا ' where id = 'RO';
update countries set short_name = 'RS' , name_en = 'Serbia' , name_ar = 'صربيا ' where id = 'RS';
update countries set short_name = 'RU' , name_en = 'Russian Federation' , name_ar = 'الاتحاد الروسي ' where id = 'RU';
update countries set short_name = 'RW' , name_en = 'Rwanda' , name_ar = 'رواندا ' where id = 'RW';
update countries set short_name = 'KSA' , name_en = 'Saudi Arabia' , name_ar = 'المملكة العربية السعودية ' where id = 'SA';
update countries set short_name = 'SB' , name_en = 'Solomon Islands' , name_ar = 'جزر سليمان' where id = 'SB';
update countries set short_name = 'SC' , name_en = 'Seychelles' , name_ar = 'سيشيل ' where id = 'SC';
update countries set short_name = 'SD' , name_en = 'Sudan' , name_ar = 'سودان' where id = 'SD';
update countries set short_name = 'SE' , name_en = 'Sweden' , name_ar = 'السويد ' where id = 'SE';
update countries set short_name = 'SG' , name_en = 'Singapore' , name_ar = 'سنغافورة ' where id = 'SG';
update countries set short_name = 'SI' , name_en = 'Slovenia' , name_ar = 'سلوفينيا ' where id = 'SI';
update countries set short_name = 'SK' , name_en = 'Slovak Republic' , name_ar = 'الجمهورية السلوفاكية ' where id = 'SK';
update countries set short_name = 'SL' , name_en = 'Sierra Leone' , name_ar = 'سيراليون ' where id = 'SL';
update countries set short_name = 'SM' , name_en = 'San Marino' , name_ar = 'سان مارينو' where id = 'SM';
update countries set short_name = 'SN' , name_en = 'Senegal' , name_ar = 'السنغال ' where id = 'SN';
update countries set short_name = 'SO' , name_en = 'Somalia' , name_ar = 'الصومال' where id = 'SO';
update countries set short_name = 'SR' , name_en = 'Suriname' , name_ar = 'سورينام ' where id = 'SR';
update countries set short_name = 'SS' , name_en = 'South Sudan' , name_ar = 'جنوب السودان' where id = 'SS';
update countries set short_name = 'ST' , name_en = 'Sao Tome and Principe' , name_ar = 'ساو تومي وبرينسيبي' where id = 'ST';
update countries set short_name = 'SV' , name_en = 'El Salvador' , name_ar = 'السلفادور ' where id = 'SV';
update countries set short_name = 'SX' , name_en = 'Sint Maarten (Dutch part)' , name_ar = 'سانت مارتن (الهولندية)' where id = 'SX';
update countries set short_name = 'SY' , name_en = 'Syria' , name_ar = 'تايوان والصين ' where id = 'SY';
update countries set short_name = 'SZ' , name_en = 'Swaziland' , name_ar = 'سوازيلاند ' where id = 'SZ';
update countries set short_name = 'TC' , name_en = 'Turks and Caicos Islands' , name_ar = 'جزر توركس و كايكوس' where id = 'TC';
update countries set short_name = 'TD' , name_en = 'Chad' , name_ar = 'تشاد ' where id = 'TD';
update countries set short_name = 'TG' , name_en = 'Togo' , name_ar = 'توغو' where id = 'TG';
update countries set short_name = 'TH' , name_en = 'Thailand' , name_ar = 'تايلاند ' where id = 'TH';
update countries set short_name = 'TJ' , name_en = 'Tajikistan' , name_ar = 'طاجيكستان' where id = 'TJ';
update countries set short_name = 'TL' , name_en = 'Timor-Leste' , name_ar = 'تيمور ليشتي ' where id = 'TL';
update countries set short_name = 'TM' , name_en = 'Turkmenistan' , name_ar = 'تركمانستان' where id = 'TM';
update countries set short_name = 'TN' , name_en = 'Tunisia' , name_ar = 'تونس ' where id = 'TN';
update countries set short_name = 'TO' , name_en = 'Tonga' , name_ar = 'تونغا' where id = 'TO';
update countries set short_name = 'TR' , name_en = 'Turkey' , name_ar = 'تركيا ' where id = 'TR';
update countries set short_name = 'TT' , name_en = 'Trinidad and Tobago' , name_ar = 'ترينيداد وتوباغو ' where id = 'TT';
update countries set short_name = 'TU' , name_en = 'Tuvalu' , name_ar = 'توفالو' where id = 'TU';
update countries set short_name = 'TV' , name_en = 'Tuvalu' , name_ar = 'توفالو' where id = 'TV';
update countries set short_name = 'TW' , name_en = 'Taiwan' , name_ar = 'تايوان، الصين' where id = 'TW';
update countries set short_name = 'TZ' , name_en = 'Tanzania' , name_ar = 'تنزانيا ' where id = 'TZ';
update countries set short_name = 'UA' , name_en = 'Ukraine' , name_ar = 'أوكرانيا ' where id = 'UA';
update countries set short_name = 'UG' , name_en = 'Uganda' , name_ar = 'أوغندا ' where id = 'UG';
update countries set short_name = 'US' , name_en = 'United States' , name_ar = 'الولايات المتحدة الأمريكية ' where id = 'US';
update countries set short_name = 'UY' , name_en = 'Uruguay' , name_ar = 'أوروغواي ' where id = 'UY';
update countries set short_name = 'UZ' , name_en = 'Uzbekistan' , name_ar = 'أوزبكستان' where id = 'UZ';
update countries set short_name = 'VC' , name_en = 'Saint Vincent and the Grenadines' , name_ar = 'سانت فنسنت وجزر غرينادين' where id = 'VC';
update countries set short_name = 'VE' , name_en = 'Venezuela' , name_ar = 'فنزويلا ' where id = 'VE';
update countries set short_name = 'VG' , name_en = 'British Virgin Islands' , name_ar = 'الجزر العذراء البريطانية' where id = 'VG';
update countries set short_name = 'VI' , name_en = 'Virgin Islands (U.S.)' , name_ar = 'الجزر العذراء الأمريكية' where id = 'VI';
update countries set short_name = 'VN' , name_en = 'Vietnam' , name_ar = 'فيتنام ' where id = 'VN';
update countries set short_name = 'VU' , name_en = 'Vanuatu' , name_ar = 'فانواتو' where id = 'VU';
update countries set short_name = 'WS' , name_en = 'Samoa' , name_ar = 'ساموا' where id = 'WS';
update countries set short_name = 'XK' , name_en = 'Kosovo' , name_ar = 'كوسوفو' where id = 'XK';
update countries set short_name = 'YE' , name_en = 'Yemen' , name_ar = 'اليمن ' where id = 'YE';
update countries set short_name = 'ZA' , name_en = 'South Africa' , name_ar = 'جنوب أفريقيا ' where id = 'ZA';
update countries set short_name = 'ZM' , name_en = 'Zambia' , name_ar = 'زامبيا ' where id = 'ZM';
update countries set short_name = 'ZW' , name_en = 'Zimbabwe' , name_ar = 'زيمبابوي' where id = 'ZW';

/*Israel should be renamed to NULL */
update countries set name_en = 'NULL' , name_ar = 'NULL' where id = 'IL';