update sources set name_en = 'College Times', name_ar = 'كوليج تايمز' where id = 1;
update sources set name_en = 'Data aggregation', name_ar = 'تجميع البيانات' where id = 2;
update sources set name_en = 'EFA Global Monitoring Report', name_ar = 'تقرير الرصد العالمي للتعليم للجميع' where id = 3;
update sources set name_en = 'Europa World Yearbook, London: Europa Publications, Ltd.', name_ar = 'حولية يوروبا العالم، لندن: منشورات أوروبا المحدودة' where id = 4;
update sources set name_en = 'Global Competitiveness Report', name_ar = 'تقرير التنافسية العالمية' where id = 5;
update sources set name_en = 'Global Fire Power', name_ar = ' القوة العسكرية العالمية' where id = 6;
update sources set name_en = 'Global Humanitarian Assistance GHA report', name_ar = 'تقرير المساعدة العالمية الإنسانية' where id = 7;
update sources set name_en = 'Global Status Report of Road Safety', name_ar = 'تقرير الحالة العالمي للسلامة على الطرق' where id = 8;
update sources set name_en = 'Health at a Glance OECD', name_ar = 'لمحة عن الصحة (منظمة التعاون الاقتصادي والتنمية)' where id = 9;
update sources set name_en = 'HPI report', name_ar = 'تقرير HPI' where id = 10;
update sources set name_en = 'Human Development Report', name_ar = 'تقرير التنمية البشرية' where id = 11;
update sources set name_en = 'Information Technology Report', name_ar = 'تقرير تقنية المعلومات' where id = 12;
update sources set name_en = 'International Civil Aviation Organization', name_ar = 'منظمة الطيران المدني الدولي' where id = 13;
update sources set name_en = 'International Labour Organization', name_ar = 'منظمة العمل الدولية' where id = 14;
update sources set name_en = 'International statistics on crime and justice', name_ar = 'الإحصاءات الدولية عن الجريمة والعدالة' where id = 15;
update sources set name_en = 'KSA Central Department of Statistics and Information', name_ar = 'KSA مصلحة الإحصاءات العامة والمعلومات' where id = 16;
update sources set name_en = 'Legatum prosperity index', name_ar = 'مؤشر الرخاء لليغاتوم ' where id = 17;
update sources set name_en = 'Multiple', name_ar = 'متعددة' where id = 18;
update sources set name_en = 'N / A', name_ar = 'N / A' where id = 19;
update sources set name_en = 'Net Index report produced by Ookla', name_ar = 'صافي تقرير مؤشر تنتجها Ookla' where id = 20;
update sources set name_en = 'OECD', name_ar = 'منظمة التعاون الاقتصادي والتنمية' where id = 21;
update sources set name_en = 'OECD - Healthcare at a Glance', name_ar = 'OECD - الرعاية الصحية في لمحة' where id = 22;
update sources set name_en = 'OECD indicators', name_ar = 'مؤشرات OECD' where id = 23;
update sources set name_en = 'OECD Reports', name_ar = 'تقارير منظمة التعاون الاقتصادي والتنمية' where id = 24;
update sources set name_en = 'Reporters Without Borders', name_ar = 'منظمة مراسلون بلا حدود' where id = 25;
update sources set name_en = 'Social Progress Imperative', name_ar = 'منظمة إلزام (حتمية) التقدم المجتمعى' where id = 26;
update sources set name_en = 'The World Factbook', name_ar = 'كتاب الحقائق العالمي' where id = 27;
update sources set name_en = 'UNStats', name_ar = 'إحصاءات الأمم المتحدة' where id = 28;
update sources set name_en = 'United Nations Conference on Trade and Development', name_ar = 'مؤتمر الأمم المتحدة للتجارة والتنمية' where id = 29;
update sources set name_en = 'United Nations Office on Drugs and Crime', name_ar = 'مكتب الأمم المتحدة للمخدرات والجريمة' where id = 30;
update sources set name_en = 'US Energy Information Administration', name_ar = 'إدارة معلومات الطاقة الأمريكية' where id = 31;
update sources set name_en = 'WEC Energy Efficiency Indicators', name_ar = 'مؤشرات كفاءة الطاقة لمجلس الطاقة العالمي' where id = 32;
update sources set name_en = 'WEF Gender Gap Report', name_ar = 'تقرير المنتدى الاقتصادي العالمي للفجوة بين الجنسين ' where id = 33;
update sources set name_en = 'WEF Global Information Technology Report - Networked Readiness Index', name_ar = 'تقرير المنتدى الاقتصادي العالمي  لتكنولوجيا المعلومات - مؤشر الجاهزية الشبكية' where id = 34;
update sources set name_en = 'World Bank', name_ar = 'البنك الدولي' where id = 35;
update sources set name_en = 'World Bank Group, Doing Business', name_ar = 'مجموعة البنك الدولي، تقرير ممارسة أنشطة الأعمال' where id = 36;
update sources set name_en = 'World Development Report', name_ar = 'تقرير عن التنمية في العالم' where id = 37;
update sources set name_en = 'World Happiness Report', name_ar = 'تقرير السعادة العالمي' where id = 38;
update sources set name_en = 'World Health Organization', name_ar = 'منظمة الصحة العالمية' where id = 39;
update sources set name_en = 'KSA Ministry of Higher Education', name_ar = 'وزارة التعليم العالي السعودية' where id = 40;
update sources set name_en = 'Free', name_ar = 'مجانا' where id = 41;
update sources set name_en = 'Global Medical Trends Report', name_ar = 'تقرير الاتجاهات الطبية العالمية' where id = 42;
update sources set name_en = 'INRIX', name_ar = '' where id = 43;
update sources set name_en = 'National Center for Assessment in Higher Education', name_ar = 'المركز الوطني للتقييم فى التعليم العالى' where id = 44;
update sources set name_en = 'OECD Report: Public and Private Schools', name_ar = ' تقرير منظمة التعاون الاقتصادي والتنميه - المدارس الأهلية و الخاصة ' where id = 45;
update sources set name_en = 'Unesco Report', name_ar = 'تقرير اليونيسكو' where id = 46;
update sources set name_en = 'World Bank Institute - KAM booklet', name_ar = 'معهد البنك الدولي' where id = 47;
update sources set name_en = 'Economist Intelligence Unit', name_ar = 'وحدة الخبراء الاقتصاديين' where id = 48;
update sources set name_en = 'Global Humanitarian Assistance GHA report', name_ar = 'تقرير المساعدة العالمية الإنسانية' where id = 49;
update sources set name_en = 'Gallup world Poll', name_ar = 'استطلاع الرأي العالمي لغالوب' where id = 50;
update sources set name_en = 'SAMA - Annual Statistics', name_ar = 'مؤسسة النقد العربي السعودي - الاحصاءات السنوية' where id = 51;
update sources set name_en = 'Human Capital Report', name_ar = 'تقرير رأس المال البشري' where id = 52;
update sources set name_en = 'Happy Planet Index', name_ar = 'منظمة التعاون الاقتصادي والتنمية - قيمة محسوبة' where id = 53;
update sources set name_en = 'OECD - Calculated', name_ar = '' where id = 54;
update sources set name_en = 'UN Data', name_ar = 'بيانات الأمم المتحده' where id = 55;
update sources set name_en = 'World Bank - Calculated', name_ar = 'البنك الدولي - قيمه محسوبه' where id = 56;
update sources set name_en = 'World by Map', name_ar = '' where id = 57;
update sources set name_en = 'World Justice Project', name_ar = 'مشروع العدالة العالمية' where id = 58;
